x-app: &app
  build: .
  environment:
    DATABASE_URL: "http://sqld:8080"
    CACHE_URL: "redis://valkey:6379"
  depends_on:
    sqld:
      condition: service_healthy
    valkey:
      condition: service_healthy

services:
  migrate:
    <<: *app
    command: ["pnpm", "exec", "drizzle-kit", "migrate"]
    restart: "no"

  app:
    <<: *app
    command: ["node", "index.mjs"]
    ports:
      - "3000:3000"
    depends_on:
      sqld:
        condition: service_healthy
      valkey:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  sqld:
    image: ghcr.io/tursodatabase/libsql-server:v0.24.33
    volumes:
      - sqld-data:/var/lib/sqld
    healthcheck:
      # A poor man's way to check if sqld is up and accepting connections
      # since the image lacks wget or curl.
      test:
        - CMD-SHELL
        - timeout 1 cat < /dev/tcp/localhost/8080 ; [ $? -ne 1 ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  valkey:
    image: valkey/valkey:8-alpine
    command: ["valkey-server", "--appendonly", "yes"]
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  sqld-data:
  valkey-data:
