packages:
  - "packages/*"
  - "apps/*"

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

catalog:
  "@tanstack/react-router": 1.167.0
  "@tanstack/react-start": 1.166.11
  "@types/better-sqlite3": 7.6.13
  "@types/node": 24.1.0
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 6.0.1
  better-sqlite3: 12.2.0
  drizzle-kit: 0.31.9
  drizzle-orm: 0.45.1
  hono: 4.12.8
  husky: 9.1.7
  nitro: 3.0.260311-beta
  oxfmt: 0.40.0
  oxlint: 1.55.0
  react: 19.2.4
  react-dom: 19.2.4
  turbo: 2.8.17
  typescript: 5.9.3
  vite: 8.0.0
