packages:
  - "packages/*"
  - "apps/*"

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - workerd

catalog:
  "@tanstack/react-router": 1.167.3
  "@tanstack/react-start": 1.166.14
  "@types/better-sqlite3": 7.6.13
  "@types/node": 24.12.0
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 6.0.1
  better-sqlite3: 12.8.0
  drizzle-kit: 0.31.9
  drizzle-orm: 0.45.1
  hono: 4.12.8
  husky: 9.1.7
  nitro: 3.0.260311-beta
  oxfmt: 0.41.0
  oxlint: 1.55.0
  oxlint-tsgolint: 0.17.0
  react: 19.2.4
  react-dom: 19.2.4
  turbo: 2.8.17
  typescript: 5.9.3
  vite: 8.0.0
  wrangler: 4.73.0
