name: "acme"

services:
  dev:
    hostname: container
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      TURBO_TELEMETRY_DISABLED: "1"
      STORAGE_SIGNING_KEY: "devcontainer-dummy-signing-key"
