name: "ygoma"

services:
  dev:
    hostname: container
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    environment:
      TURBO_TELEMETRY_DISABLED: "1"
