/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestUploadRouteImport } from './routes/test-upload'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SentryTestIndexRouteImport } from './routes/sentry-test/index'
import { Route as SentryTestSsrErrorRouteImport } from './routes/sentry-test/ssr-error'
import { Route as SentryTestErrorRouteImport } from './routes/sentry-test/error'

const TestUploadRoute = TestUploadRouteImport.update({
  id: '/test-upload',
  path: '/test-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentryTestIndexRoute = SentryTestIndexRouteImport.update({
  id: '/sentry-test/',
  path: '/sentry-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentryTestSsrErrorRoute = SentryTestSsrErrorRouteImport.update({
  id: '/sentry-test/ssr-error',
  path: '/sentry-test/ssr-error',
  getParentRoute: () => rootRouteImport,
} as any)
const SentryTestErrorRoute = SentryTestErrorRouteImport.update({
  id: '/sentry-test/error',
  path: '/sentry-test/error',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-upload': typeof TestUploadRoute
  '/sentry-test/error': typeof SentryTestErrorRoute
  '/sentry-test/ssr-error': typeof SentryTestSsrErrorRoute
  '/sentry-test/': typeof SentryTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-upload': typeof TestUploadRoute
  '/sentry-test/error': typeof SentryTestErrorRoute
  '/sentry-test/ssr-error': typeof SentryTestSsrErrorRoute
  '/sentry-test': typeof SentryTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-upload': typeof TestUploadRoute
  '/sentry-test/error': typeof SentryTestErrorRoute
  '/sentry-test/ssr-error': typeof SentryTestSsrErrorRoute
  '/sentry-test/': typeof SentryTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-upload'
    | '/sentry-test/error'
    | '/sentry-test/ssr-error'
    | '/sentry-test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-upload'
    | '/sentry-test/error'
    | '/sentry-test/ssr-error'
    | '/sentry-test'
  id:
    | '__root__'
    | '/'
    | '/test-upload'
    | '/sentry-test/error'
    | '/sentry-test/ssr-error'
    | '/sentry-test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestUploadRoute: typeof TestUploadRoute
  SentryTestErrorRoute: typeof SentryTestErrorRoute
  SentryTestSsrErrorRoute: typeof SentryTestSsrErrorRoute
  SentryTestIndexRoute: typeof SentryTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-upload': {
      id: '/test-upload'
      path: '/test-upload'
      fullPath: '/test-upload'
      preLoaderRoute: typeof TestUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentry-test/': {
      id: '/sentry-test/'
      path: '/sentry-test'
      fullPath: '/sentry-test/'
      preLoaderRoute: typeof SentryTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentry-test/ssr-error': {
      id: '/sentry-test/ssr-error'
      path: '/sentry-test/ssr-error'
      fullPath: '/sentry-test/ssr-error'
      preLoaderRoute: typeof SentryTestSsrErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentry-test/error': {
      id: '/sentry-test/error'
      path: '/sentry-test/error'
      fullPath: '/sentry-test/error'
      preLoaderRoute: typeof SentryTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestUploadRoute: TestUploadRoute,
  SentryTestErrorRoute: SentryTestErrorRoute,
  SentryTestSsrErrorRoute: SentryTestSsrErrorRoute,
  SentryTestIndexRoute: SentryTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
